### ISSUE TITLE
Exception with an error code: 0x5 (SPXERR_INVALID_ARG) when trying to Enroll

### ISSUE THREAD

**Issue by QuackersCoder** [Microsoft/Cognitive-SpeakerRecognition-Windows#12]
Hi I'm getting the following error when trying to Enroll a profile. 

The profile is an Identification profile , and exists. 

The error occurs when i call 
  result = await client.EnrollProfileAsync(profile, audioConfig);

I am trying to create, then enroll later... 
When i create  a voiceprofile to pass into the enrollment like this 

_var profile = new VoiceProfile(profileId)_

..rather than creating one with the client seems to be triggering the error. , Does the Enrollment need the profile creating just before? I cannot see a client method for retrieving a created voiceprofile

Version: Microsoft.CognitiveServices.Speech SDK 1.12.1

**Error** 
Exception with an error code: 0x5 (SPXERR_INVALID_ARG)
**Source** 
Microsoft.CognitiveServices.Speech.csharp

**Stack trace**
   at Microsoft.CognitiveServices.Speech.Internal.SpxExceptionThrower.ThrowIfFail(IntPtr hr)
   at Microsoft.CognitiveServices.Speech.Internal.SpxFactory.GetDataFromHandleUsingDelegate(GetResultDelegate functionPtr, InteropSafeHandle handle, Int32 maxCharCount)
   at Microsoft.CognitiveServices.Speech.VoiceProfileEnrollmentResult..ctor(IntPtr resultHandlePtr)
   at Microsoft.CognitiveServices.Speech.VoiceProfileClient.<>c__DisplayClass6_0.<EnrollProfileAsync>b__0(InteropSafeHandle h)
   at Microsoft.CognitiveServices.Speech.VoiceProfileClient.<>c__DisplayClass10_0`1.<RunAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Ossa.VoiceIdentification.Common.SpeechWrapper.<Enroll_TextIndependentVerification>d__19.MoveNext() in C:\Projects\VoiceIdentification\src\Ossa.VoiceIdentification.Common\SpeechWrapper.cs:line 269
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Ossa.VoiceIdentification.WindowsClient.Form1.<btnEnrollMicTextIndependant_Click>d__19.MoveNext() in C:\Projects\VoiceIdentification\src\Ossa.VoiceIdentification.WindowsClient\Form1.cs:line 181
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by QuackersCoder** [comment]
Think this may be the wrong project re raised in Azure-Samples
/cognitive-services-speech-sdk
